# Results Section

<iframe width="560" height="315" src="https://www.youtube.com/embed/hxfUJGjXDUo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

The results section is the link between the methods and the discussion section. It should provide a clear and concise summary of the findings from the research study. The authors should report the findings that were estimated using the approaches presented in the methods section, in the same order as in the methods section and the writing should be free from interpretations. 

It may appear that the results is the simplest section to write. However, authors must carefully prepare this section to maintain the readers’ attention and interest, and to facilitate understanding of the study. Although the results section generally only contains the quantitative information (except for qualitative and mixed-methods studies), it should still be easy to follow and understand. Presenting the findings in the results section in the same sequence as the procedures were presented in the methods section can improve the flow of the paper. In general, the results section has the following order: (i) the study sample or population characteristics, (ii) findings from the primary analysis, (iii) findings from the secondary analyses, and (iv) any additional findings that may be important to the understanding of the readers.

Below are the key characteristics and typical organization of a results section in a scientific paper based on an observational study in population and public health, along with some common pitfalls and tips.

## Key characteristics and organization of a results section

1.	**Study sample characteristics and descriptive statistics**

    a.	Generally, the characteristics of the study sample are described first in the results section. This can be accompanied by a flowchart detailing the inclusion and exclusion criteria that were applied to generate the final analytic sample.

    b.	Rather than being overly detailed, the sample characteristics should be summarized using key information. A table containing more detailed information can be referenced to ensure the results are concise.

    c.	The results section can also include the descriptive statistics for the outcome and explanatory variable, including the prevalence of a categorical outcome and/or exposure, the incidence rates of a categorical outcome in prospective studies and, the mean and standard deviation of a continuous outcome and/or exposure. Typically, descriptive statistics are presented in Table 1.

2.	**Findings of the primary analysis**

    a.	The findings of the main research question, based on the primary analysis, are presented in this section. 

    b.	Estimates from the crude/unadjusted and the adjusted models evaluating the relationship between the exposure and outcome can be reported. Authors should note whether the relationship changed or remained the same following adjustment. 

    c.	Generally, the findings from the adjusted model for the main relationship under investigation are presented in table 2. When reporting the estimates in table 2, use caution not to introduce the table 2 fallacy [@westreich2013table].

3.	**Findings from the secondary analyses**

    a.	If interaction, effect modification or sub-group analyses were performed, the findings from these analyses should be presented in relation to the primary research question. No new interaction should be added without providing proper justification in the earlier sections.

    b.	The relationships between the confounders and the outcome can also be described (but, not interpreted), in order to help readers understand the relationship under investigation.

4.	**Any additional findings to highlight**

    a.	Additional findings from sensitivity analyses or other interesting findings can also be highlighted.

The results section should describe the study findings without being unduly pedantic or repetitive. Authors are discouraged to detail every analysis details when presenting the corresponding results and to describe redundant findings. As mentioned in the previous chapter, the results section should describe all the tables and figures included in the article. However, it is unnecessary to describe them in great detail. As the tables and figures are used to portray a large amount of data in an efficient manner, the text in the results section should summarize the key findings that are important to convey to the readers. These can include trends or patterns present in the data, group comparisons, or key estimates.

--------------------------------------------------------------------------------------------------

Although, ideally, the results section presents the study findings in a clear and objective manner, it should also be presented as a ‘story’. That is, the information should have a logical flow. Some authors may opt to write the results section before writing the other sections. Regardless of the order in which you write your scientific article, you should always keep in mind the ‘whole story’ of your study and what it is you are trying to convey in your paper. Based on the research question that you posed in the introduction section and the statistical procedures you explained in the methods section, the results section provides readers with the findings from your study. You’ll have the opportunity to provide explanations for these results in the discussion section. Whichever section you choose to write first, they should all work together to tell the research ‘story’. 

## Common pitfalls

-	The most common pitfall is including components of the methods and discussion sections in the results section. There should be a distinct separation between the methods, results and discussion sections. This separation has been encouraged as readers may be interested in different sections; some may be more interested in the methods because they wish to replicate them, some may be only interested in reading the results to include them in a meta-analysis, and some may skim through the results as they are more concerned with the interpretation in the discussion section [@heard2016scientist, p.99-119]. Having a clear separation of the sections can help the readers quickly find the elements they are most interested in.
-	Not reporting clearly which findings are from the primary or secondary or sensitivity analyses can be confusing to the reader.
- Focusing too heavily on the crude or unadjusted analysis should be avoided, as most unadjusted estimates from observational studies are likely confounded.
- Perhaps most importantly, it is crucial to report the findings objectively, without trying to influence the readers. For example, it is misleading to write an effect size was “marginally significant” when it was not statistically significant at a 5% significance level.
-	In addition, Kotz and Cals argue that only presenting p-values can be misleading. They encourage the inclusion of 95% confidence intervals as they provide additional information such as the direction of the effect size, the size of the effect estimate and the degree of precision [@kotz2013effective5].

## Tips

1. The results are generally presented in the past tense. However, when referencing a table or a figure, they may be described in the present tense.
2. Avoid reporting redundant numbers, as this can make the paragraphs dense. For example, if you are reporting the 95 confidence intervals of your estimates, it may not be necessary to report the p-values.
3. Only present the results and data that is necessary for readers to understand why the conclusion you are drawing about the research question is justified. As with all the other sections, excess information can be distracting from the central point of your article.
4. The results section should be absent of any interpretation of the findings or data. You will have an opportunity to interpret the results in the discussion section.
5. Having sub-section headings can improve the readability and flow of the results section.
6. Always be consistent in the way you report the study findings, including the order of presentation (e.g., the exposed group followed by the control group), the number of decimals, the terms used and the units of measurement. In addition, it is encouraged to include the absolute numbers when presenting relative measures (e.g., if reporting proportions, provide the counts in parentheses).
