# Discussion Section

The discussion section is the final component of a scientific paper based on the format of IMRad (Introduction, Methods, Results and Discussion). In comparison to the other sections, the discussion section allows the authors the most freedom in writing and structuring the text, making it both liberating and challenging to write.

The objective of a discussion section is to answer the research questions that were raised in the introduction by interpreting the findings presented in the previous results section. Further, the discussion section gives the authors the opportunity to explain the study findings and their implications to a broader audience. The introduction and the discussion sections are intrinsically connected; the questions posed in the introduction are addressed in the discussion, and the key problems that are discussed in detail in the discussion were introduced earlier in the introduction. In the introduction section, the author starts with broad background information on the topic and gradually narrow down to present the specific research question(s) and the reasons supporting the need to conduct the study. The discussion section is where the author gets to address all the components touched upon in the introduction, turn the data presented in the results section into “knowledge” and provide a compelling argument on how the findings of the study contribute to existing knowledge, and why it was worthwhile to do the study.

## Components of a discussion section

Keeping the connection between the introduction and the discussion section in mind, the discussion section follows an inversed funnel shape that gradually broadens, as opposed to the narrowing funnel shape that describes the components of the introduction section (Chapter 1). The discussion starts narrow, with responses to the specific research questions, and gradually broadens as the study findings are compared to previous studies and placed in the wider context of the topic. The strengths and limitations of the study are then discussed, and future directions are provided. Below, we discuss the components of the discussion section in detail.

1.	**Summary of the main findings**
- The summary of the main findings provides answers to the specific research question that was posed in the introduction section. If there were many research questions or if the question was very complex, the author can briefly remind the readers what the research question was at a high level. The key findings for the main research question should be interpreted first, followed by findings from any secondary analyses.
- The authors should explicitly and concisely state the verdict on the research question when summarizing the main findings, as this is the key information that readers are looking for.
- Overreaching conclusions or overgeneralizations of the study findings should be avoided. The results should be interpreted based solely on the people who were included in the study sample. Though, it is reasonable for authors to make speculations based on the results, they should refrain from misrepresenting speculation as inference [@heard2016scientist, p.120-125].

2.	**Contextualizing the study findings within the existing literature**
-	In the introduction section, the objective of presenting the background knowledge was to introduce the readers to the topic and to set the tone for the rest of the manuscript. In the discussion section, the results of the study are interpreted. Therefore, in this section, the author can expand on the high-level information introduced in the beginning of the manuscript and contextualize the findings of the study within the literature. 
-	The study findings are compared to previous studies to contextualize them in the existing literature. By comparing the study findings to similar previous studies, the author can determine whether their study findings agreed with or were contradictory to previous studies. 
-	If the findings of the study were similar, the author should explain why their new study was needed, and how it contributes to the literature. If the findings were conflicting, the author can explore the reasons for this discrepancy. 
-	While relating the study findings to other studies and placing the current study in the literature are important components of a discussion section, it’s main focus should be on how the analysis and findings of this study adds to the existing body of evidence.

3.	**Clinical or public health relevance of the study findings**
-	The target audience of a scientific article in population and public health research may include clinicians, other researchers, patient communities and members of the general public with an interest in the specific health topic. It is critical to stress the relevance of the study findings to the target audience. The author should keep the specific target audience in mind when explaining why the study findings are significant. For example, if the study’s goal was to evaluate the effectiveness of a drug in treating a particular condition, the author may emphasize how the findings are important for patients, and how they may affect clinical decisions for healthcare providers.

4.	**Strengths and limitations**
-	In this sub-section, the author explains the study’s specific strengths and limitations. This is a particularly challenging and important section to compose as reviewers and readers will scrutinize it closely.
-	The strengths and limitations that are unique to the study should be discussed. For example, authors should address how the study has done something new, how it adds to current knowledge, or how it supplements, reinforces, or contradicts previous research. 
-	Similarly, rather than discussing limitations that are generic or applicable to most studies, the limitations that are specific to the current study should be highlighted. Limitations can be related to the data, design or the methods used in the study. Unmeasured confounding specific to the study, untestable assumptions related to the study, and lost-to-follow-up or missing data are all examples of limitations. In addition, it is crucial to describe not only the limitations, but also the measures taken to mitigate them.
-	It is critical to clearly state the limitations of the study. But, the discussion section is also where the author can defend their work and demonstrate to readers and reviewers what steps were taken to mitigate the limitations and to strengthen the robustness of the findings. 
-	It can be good practice to approach the strengths and limitations section as if it was a critical appraisal or a peer-review. Authors can ask themselves: what kinds of issues might the reviewers raise about the study? What are the potential biases? The author can anticipate these questions in advance and prepare the responses accordingly. For example, when discussing potential sources of bias or imprecision, the author can discuss the direction and magnitude of the bias or imprecision, as well as how this may affect the study findings, and what efforts were made to minimize the bias.
-	When discussing the strengths and limitations, the author can elucidate on the robustness and the generalizability of the study findings, as well as the reproducibility of the study. 

5.	**Future directions and implications**
-	Depending on the focus of the paper, the discussion section should describe some of the potential study implications for clinical practice and/or research. Cals and Kotz also suggest that simply stating “further research is needed” is insufficient [@cals2013effective5]. Based on the study findings, what are the next steps for the research in this area? The author should make recommendations for future research, based on the remaining unanswered questions or unavailable variables, measures or outcomes in the data. The description of future directions should be short and specific.
-	It may be a good idea to conclude the paper with an overall ‘big-picture’ of the study; what is the take-home message now that you’ve presented the ‘story’ of your study to the readers? The summary of the study implications should be clear and concise, written in a such way that general readers can easily grasp the key message of the study. 

## Additional tips 

The purpose of the discussion section is: to provide readers with a summary of the main findings and, based on these, the answers to the central research questions posed in the introduction section, to contextualize the study findings by comparing them to previous work, and to analyze the study’s specific strengths and limitations. Through this process, the author expands on the findings of the study in order to provide the most persuasive interpretations and find the broadest significance, as well as describe the study implications and offer future directions in the specific research area. The following are some additional do’s and dont’s for a discussion section.

```{r table6, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
tabl <- '
Table 1: Do\'s and Dont\'s of writing a discussion section

| **Do’s**                                                                                                                                                                                                                       | **Dont’s**                                                                                                                                                                                                                                                                                                             |
| :----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| It is okay to make speculations based on the research findings, however, make sure that you present these as speculations and not as causal inferences. Also, be clear about the study limitations                             | Do not present in detail all of the possible sensitivity analyses or all of the sensitivity analyses that you conducted. Only discuss those that contribute to the robustness of your interpretation of the study findings                                                                                             |
| Discuss if there was anything surprising about the findings or if the results went against the initial hypothesis                                                                                                              | Do not omit any potential alternative explanations of the findings of your study. In the discussion section, reviewers will mainly be focused on whether the interpretations and conclusions drawn were supported by the evidence presented, and whether there were any alternative explanations that may be plausible |
| Present the key limitations of the study and how they may have impacted the results                                                                                                                                            | Do not restate the findings too repetitively. The paper should end with a clear summarizing statement of the manuscript’s storyline.                                                                                                                                                                                   |
| Provide the answer to the research questions at the beginning of the discussion section. Ensure that your answer is in line with the research question presented in the introduction section.                                  | Do not interpret the absence of statistical significance as the absence of association. The findings should not be interpreted solely based on the p-values of the statistical tests [@lederer2019control]                                                                                                             |
| Learn to criticize your own work and acknowledge the limitations transparently. But, also use the discussion section as an opportunity to defend your work and to talk about the steps that were taken to mitigate limitations |                                                                                                                                                                                                                                                                                                                        |
'
cat(tabl) # output the table in a format good for HTML/PDF/docx conversion
```
