# Title and Abstract

A well composed title and abstract are critical to a good scientific article because they are the two components that most people will read first. During the submission process to journals, the abstract is the first part of the manuscript that editors will read to decide whether to send the manuscript for review. Once the article is published, the abstract is the first part most readers will read, and sometimes, the only part of the article that the readers are able to consume. The abstract is also an important indication of the quality of the research. For example, most scientific conferences will base their selection of presentations solely on the abstract. Therefore, a well-written title and abstract are essential for the publication of a scientific article as well as for conference submissions. They are also crucial for conveying a clear, informative story to the readers who may only get to read the title and the abstract. In this chapter, we discuss characteristics of a good abstract and title as well as some tips and examples. 

## Components of an abstract

As the abstract gives editors, reviewers and readers the first impression of the study, it is critical that it contains all the necessary information, including the study aims, main findings and interpretations. Generally, abstracts need to be short, between 200 to 300 words, and are structured in subsections. The headings of the subsections depend on the journal or the conference, but the essential components tend to be consistent. Below we present four subsections that are often used to compose a structured abstract: background, methods, results and discussion.

1.	**Background – “What is known in the literature, why is the current study needed?”**
- The background should contain a very brief summary of the corresponding background section of the manuscript, laying out what is the “key” evidence in the literature known to date and what is the gap in the knowledge that justifies the present study. This subsection should clearly identify the rationale for conducting the study. Following the rationale, the study aim or the main research question must be clarified.

2.	**Methods – “What did you do?”**
- The abstract should describe what methods were used to answer the scientific question or to accomplish the study aim. This section should have a brief explanation of the data source used in the study, the study time frame and the statistical methods used to conduct the primary analysis.

3.	**Results – “What did you find?”**
-	In the abstract, key findings from the primary analysis should be presented. The analytic sample or the study population should be clearly described, as well as the effect size estimates such as the odds ratios, hazard ratios and the 95% confidence intervals. Reporting 95% confidence intervals rather than p-values can inform the readers about the strength, direction and variability of the estimates. 

4.	**Discussion – “What do the results mean? And so what?”**
- The main findings should be interpreted clearly and accurately. It is crucial to interpret the results carefully as to not mislead the readers. The discussion section also needs to convey what the key implications of the findings are. These may be implications for future research and for the general understanding of the topic under investigation. It is also a good idea to discuss the main limitations of the study. Particularly for observational studies, it is important to be transparent about any major limitations that might limit the internal validity and generalizability of the study.

## Characteristics of a good abstract

A well-structured abstract, even without the subsections, should **describe** the research questions, aims and methods; be **critical** of the key findings and major limitations; and be insightful, discussing the key contribution to the literature and implications of the study. 
The title and abstract of the study are the components that are indexed in the literature databases and are openly accessible to all readers, even when the study is published in a subscription-based journal. Therefore, some readers may only be able to access the abstract, which is why it’s crucial for the abstract to be **standalone**. It should summarize all the important aspects of the study, and just by reading the abstract, the readers should be able to gain an understanding of what was done, how it was done and what was found. As abstracts are required to be short and succinct, it should avoid having too many technical details or nuanced discussion. Writing a good abstract involves **highlighting the study aim** and gap in the literature, and describing how the study tried to address the gap or to contribute to current knowledge. Finally, by reading the abstract, it should be clear to readers what the **key take home message** is. 

## Tips for writing an abstract

1. Write the paper first; then, re-read the paper and think about the purpose of the study, and the implications of the main finding. Keep in mind what the key messages you want to convey to readers are. It may help to write down the keywords or key messages in a list before starting to write the abstract.
2. Take time to write, revise and re-write the abstract. The abstract is important; journal editors, conference abstract reviewers and other researchers will judge the quality of the research based on the abstract. A well-written abstract can leave a good impression.
3. The abstract should be written in an active voice; many journals support the use of active voice over the use of passive voice (with the exception of the methods section). Most concepts and results are conveyed more succinctly and clearly when written in an active voice [@nature2021portfolio;@thebmj2021authors].
4. When using subsections, each section should have two to three sentences. Additionally, the language should be simple and free of jargon/terms that are too discipline-specific.
5. Abstract should be free of any citations or references, and the use of abbreviations should be minimal. The use of Greek letters or special characters should be avoided, as it might cause formatting issues in some indexing databases.
6. While re-reading the abstract, note if all the sections flow coherently. Do the reported results match the research question? Are the implications specific to the results presented?
7. With the limited word count allocated to the abstract, it is likely that there will be no space to discuss the results of the sensitivity analyses. If space permits, it is acceptable to simply report that the sensitivity analyses were performed to test the robustness of the main findings, without necessarily presenting all the results.
8. The EQUATOR Network provides [guidelines for reporting observational studies in a conference abstract](https://www.strobe-statement.org/download/strobe-checklist-conference-abstracts) [@strobe2021abstract]. Some of the key elements of the guidelines include:

    a. Title should include the study’s design, such as cohort study, case-control or cross-sectional study.
    b. In the abstract, study design and specific objectives should be clarified.
    c. The methods section should include the study setting, the timeframe, and describe the study participants, including the eligibility criteria and the statistical methods.
    d. The results section should include the number of participants included in the analytic sample, the main results, including the estimates of associations, and the measures of variability and uncertainty.
    e. The conclusions section should include the general interpretation of the study results.

## Title of a scientific article

Even before the abstract, the title is the first thing readers look at, hence it is a very important element of a scientific article. Though the title shouldn’t be “click-bait”, it should still pique the interest of the readers. Moreover, it should be brief and straightforward while still conveying the central story of the paper or the main research question. The title should be coherent and consistent with the abstract, but not completely copy the main text. As the title is indexed in the databases, it should contain all the important keywords to facilitate the literature search. In population and public health research, we propose three types of titles: descriptive titles, informative/assertive titles, and inquisitive titles. **Descriptive titles** are used most often, and usually describe the main topic or association that is under investigation. The **informative or “assertive sentence” titles** [@heard2016scientist, p.79–83] are not always preferred by all readers since they may be perceived as being too conclusive without supporting arguments or explanations, but they are catchy and summarize the key message of the study. Finally, **inquisitive titles** actually present the main scientific question that is addressed in the research paper. Table 1 presents some examples in the literature of different types of titles in epidemiology and health sciences research.

```{r table7, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
tabl <- '
Table 1: Titles of scientific articles in epidemiology, population and public health research

||
|---	|
|     [Study   of mirtazapine for agitated behaviours in dementia (SYMBAD): a randomised, double-blind,   placebo-controlled trial](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)01210-1/fulltext)     <br> This   is an example of a descriptive title which presents the name of the trial   presented, SYMBAD, and also describes the design of the study, which was a   randomised controlled trial.    	|
|     [Obesity   management as a primary treatment goal for type 2 diabetes: time to reframe   the conversation](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(21)01919-X/fulltext)    <br>  This   is another example of a descriptive title. We can assume that the keywords of   this study are “obesity management” and “treatment for type 2 diabetes”. The   latter part of the title “time to reframe...” also suggests that the study   might be presenting a novel aspect to existing clinical guidelines for   treatment of diabetes.    	|
|     [Effect   of dietary sources of calcium and protein on hip fractures and falls in older   adults in residential care: cluster randomised controlled trial](https://www.bmj.com/content/375/bmj.n2364)     <br> This   is also a descriptive title; in this title the authors present the main   association under investigation (“effect of dietary sources of calcium and   protein” on “hip fractures and falls”), and the population group of interest   (older adults in residential care), as well as the study design (cluster   randomised controlled trial).    	|
|     [Sustained   virological response from interferon-based hepatitis C regimens is associated   with reduced risk of extrahepatic manifestations](https://www.sciencedirect.com/science/article/abs/pii/S0168827819304623)     <br> This   is an example of an assertive sentence title; the title indicates the main   finding of the study, which was that the sustained virological response from   a treatment was associated with reduced risk of extrahepatic manifestations.    	|
|     [Convenience   and comfort: reasons reported for using drugs alone among clients of harm   reduction sites in British Columbia, Canada](https://link.springer.com/article/10.1186/s12954-020-00436-6)     <br> This   is an example of an informative title which gives the readers the answer to   their main research question “what were the reasons for using drugs alone?”   as “Convenience and comfort” among the study population of interest (clients   using harm reduction sites in British Columbia, Canada).     	|
|     [Are   perceived barriers to accessing health care associated with inadequate   antenatal care visits among women of reproductive age in Rwanda?](https://bmcpregnancychildbirth.biomedcentral.com/articles/10.1186/s12884-020-2775-8)     <br> This   is an example of an inquisitive title, which in itself is the main research   question that the paper is trying to answer.    	|
|     [Are   US adults with low-exposure to methylmercury at increased risk for   depression? A study based on 2011–2016 National Health and Nutrition   Examination Surveys (NHANES)](https://link.springer.com/article/10.1007/s00420-020-01592-9)     <br> This   is another inquisitive title, which also indicates the data source for the   study (2011-2016 National Health and Nutrition Examination Surveys).    	|
|     [“I   want to get better, but…”: identifying the perceptions and experiences of   people who inject drugs with respect to evolving hepatitis C virus treatments](https://link.springer.com/article/10.1186/s12939-021-01420-7)     <br> This   is an example of a qualitative study in population and public health   research, which uses a part of a quote from an interview with a study   participant to present the central aim of the study, which was to identify   the perception and experiences of people who inject drugs, with respect to   evolving hepatitis C treatments    	|
'

cat(tabl) # output the table in a format good for HTML/PDF/docx conversion
```
