# Responding to reviewer comments

Responding to peer review feedback is an integral part of the peer-reviewed publication process. Chapter 5 discussed in detail about the peer-reviewing process in biomedical research and scientific writing. We also mentioned in Chapter 5 how critical it is to consider the peer review feedback and briefly mentioned one way to organize responding to review comments, in a point-by-point response format. In this chapter, we go over how to respond to reviewer comments in greater detail and offer some pointers for responding to reviewer comments.

Firstly, once the scientific article is submitted to a peer-reviewed journal, there are generally three possible outcomes. The editors decide whether to accept the paper for publication, reject the paper for publication (either as a “desk rejection” because the article is deemed incompatible with the journal’s objectives and readership interests, or as a rejection after a review), or ask for resubmission after revision. Almost all published papers in peer-reviewed journals have gone through this revision process; thus, receiving a "revise and resubmit" decision for the manuscript is a good sign; as addressing the reviewers' comments and concerns satisfactorily is likely to result in the paper being accepted for publication. Minor and major comments, as well as comments from reviewers, associate editors, and editors, may be included in the peer review feedback. The requested revision could be a minor or major revision. After the authors resubmit with revisions, the reviewers are usually asked to go over the revisions again and decide if they are satisfactory. The editors may also provide feedback and request revisions as necessary. Sometimes this revision process takes multiple rounds of peer review. 

## Tips for revisions and responding to review comments

Similar to the submission package for manuscript, when resubmitting a manuscript the resubmission package includes a response letter to the reviewers, which generally begins by thanking the reviewers for their commentary and includes a brief description of the major changes to the revised manuscript incurred by the feedback received; it also includes the responses to reviewers’ comments, which are recommended to be organized in a point-by-point format. Each journal has its own set of rules, but in general, authors are asked to resubmit a track-change enabled revised manuscript and appendix.

As suggested previously, organizing the response to reviewer comments in a point-by-point format is a clear and concise approach to showing the reviewers how the authors considered and addressed each of the reviewers' comments and concerns. We propose tips for responding to reviewer comments below, adapted from William Noble’s rules for writing a response to reviewers [@noble2017ten] and resource for authors provided by PLOS [@plos2021peerfeedback].

- **Make a plan for revisions and responses when reading the reviewer comments**

    - Revision suggestions from reviewers and editors may include essential and non-essential (but nice to have) suggestions. While reading the comments, make a note of the essential revisions and set priority for these.
    - Consider whether you will need to conduct additional analyses in order to respond to the comments, plan time to address these accordingly.

- **Respond to everything in a point-by-point format**

    - To make the response to reviewer comments clear and comprehensive, list all comments provided by reviewers in a document and respond to all comments, even minor ones. Firstly, respond to the comment briefly, then indicate what changes/revisions/additions were made to the manuscript in response to the comment. 
    - Responding to comments in a point-by-point format can save time during subsequent rounds of review.
    - When responding to comments, make sure your responses are **specific, direct, and concise**. Excessively long responses can be both unnecessary and unhelpful.
    - It can be beneficial to use the same language and terminology as the reviewers.
    - If you believe that the comment cannot be addressed in the current manuscript, it can be listed as a limitation and/or future work to demonstrate to the reviewers that you have considered the reviewer's concern.

- **Keep track-changes in the main manuscript**

    - The journals will generally ask to resubmit the revised manuscript as a track-change enabled word document. Keep all revisions, and changes tracked. 

- **Revise the manuscript to improve the clarity of the writing**

    - *“Keep calm and take stock”* [@plos2021peerfeedback]. Remember that the goal of the peer review process is to improve science communication. Assume that reviewers have the best intentions for your manuscript, and ultimately, you should make the best of the feedback in order to improve the manuscript's quality.
    - If the reviewer misunderstood the point you are trying to make, assume that this may have happened with the readers and try to clarify the point. 
    - When responding to reviewer comments, the first reaction should be to make a change in the manuscript rather than just addressing it in response to reviewers. If the reviewer expressed concern about something, the readers might have a similar concern.
    - Try to address as many of the reviewers' requests as possible, even if you believe they are unnecessary. For example, the reviewers may request additional information on the background or methods that you believe are unnecessary. These requests, however, are harmless and will most likely add another layer to the manuscript. If the reviewers request lengthy additional information, it is possible to include this as an appendix.

- **Try to keep the response to the reviewer comments document as self-contained as possible**

    - When you revise or add new sentences or paragraphs to the manuscript in response to reviewer comments, include these revisions or new additions in quotes/different font/colour in response to reviewer comments document, so reviewers don't have to go back to the tracked manuscript to find where the revision is made.
    - Referring to a specific subsection of the manuscript (e.g. in the “Sensitivity analysis” subsection under the “Methods” section) may be more helpful than referring to a specific page number of the document because the reviewer may receive a different version of the manuscript.

- **Make time to compose the response to the reviewer comments document**

    - It is easier to be defensive and reactive to the comments than it is to maintain objectivity and clarity when responding to feedback. It is advised to *“let it sink in before writing the response”* [@kotz2014effective10] once you have received the review comments. 
    - We propose that responding to the comments immediately may result in a dismissive and defensive attitude towards the comments, and we recommend that responses to reviewers' comments be written with time and revisions. 
    - Sometimes, it can be helpful to address the “easy” comments first, and then go through multiple rounds of responses to the remaining comments. Take your time revising the response to the reviewer comments document.

- **Be mindful of the tone**

    - Always be constructive, respectful, and polite in your response to reviewers’ comments.
    - It is possible to disagree with a comment. However, if you disagree with a comment, explain why: be respectful and provide evidence from previous literature or your own work to support your point of view. Without a clear and sufficient explanation, the reviewers may make the same suggestion again in the subsequent round of review.
    - Set aside time to re-read your responses to ensure that you have written them in a calm and professional manner.

The reviewers’ comments provide us with insight into the minds of potential readers, and serves as an opportunity to improve the manuscript. Revisions almost always strengthen the papers, so take advantage of this process to improve your paper and make science communication more effective and thoughtful. A well-written resubmission package, including a response letter and point-by-point responses to reviewers’ comments, can help to improve the manuscript and ultimately lead to its publication.
