# Finding Suitable Journals

Once an article is written, the next step is to find a suitable journal and then format the journal according to the author guidelines. 

Authors can try to submit their title, abstract and keywords to try to identify journals in the following publisher specific search tools that may have matching interests. 

- [Elsevier](https://journalfinder.elsevier.com/)
- [Springer](https://journalsuggester.springer.com/)
- [Taylor and Francis](https://authorservices.taylorandfrancis.com/publishing-your-research/choosing-a-journal/journal-suggester/)
- [Wiley](https://journalfinder.wiley.com/search?type=match)
- [Sage via edanz](https://www.edanz.com/journal-selector)

Alternatively, authors could use external search tools that aggregates journal information:

- [Jane](https://jane.biosemantics.org/) (uses information from PubMed)
- [Web of Science](https://mjl.clarivate.com/home)

There exists other similar resources that authors could consider checking:

- [Open Journal Matcher](https://ojm.ocert.at/)
- [Open Access Journal Finder](https://www.enago.com/researcher-hub/journal-finder.htm)
- [Journal Guide](https://www.journalguide.com/)
- [IEEE](https://publication-recommender.ieee.org/home)
- [flourishoa](http://flourishoa.org/)
- [EndNote](https://endnote.com/product-details/manuscript-matcher/)


## Refining the scope of your search {-}

- Authors should check carefully if the journal has a mandatory open access fee or article processing cost (APC). Often these fees can be very high. For example, you can check charges per article from various open access journals [here](https://openwetware.org/wiki/Publication_fees) (please visit the specific journals to know the updated fees). If authors do not have a source of funding for these fees, they should aim for **subscription based journals**. There also exist many hybrid-type journals that supports both models.
- Other refinement criteria includes
  - Time to decision / publication (how long the journal takes to process the article)
  - CiteScore or Impact factor (IF) of the journal (IF is a measure of importance of a journal by calculating the number of times it's articles are cited)
  - Acceptance rate (among the articles that are submitted in the journal, how many of them are eventually accepted in the journal)
- Authors should be aware that there exists many [predatory journals](https://en.wikipedia.org/wiki/Predatory_publishing), and they should avoid choosing them. 
- Authors should also check the policy about posting a pre-print to preprint servers (e.g., [arXiv](https://arxiv.org/), [bioRxiv](https://www.biorxiv.org/) or [medRxiv](https://www.medrxiv.org/); see a more complete list [here](https://en.wikipedia.org/wiki/List_of_preprint_repositories)) before initial submission to a journal.

## Discounts for open-access publications {-}

If you are open to open-access publications and have funding to support it, do check with your University or affiliated institute if there are discounts available for your affiliation. For example, for UBC, there are discounts available from some open access publishers. You can find details [here](https://scholcomm.ubc.ca/open-access-publisher-discounts/). Particularly take a look at the agreement between [CRKN – Canadian Research Knowledge Network](https://www.crkn-rcdr.ca/en/open-access-publishing) and your University. 


## Academic journal through student-led initiatives {-}

There also exists many student-driven academic peer-reviewed journals, and the trainees can also consider those journals. For example, within UBC, [UBCMJ](https://ubcmj.med.ubc.ca/) is one example.
